# Generated by Django 5.1.3 on 2024-12-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('encrypted_text', models.TextField()),
                ('decrypted_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EncryptedText',
        ),
    ]
