# Generated by Django 5.1.3 on 2024-12-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0002_encryptionhistory_delete_encryptedtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionhistory',
            name='decrypted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
