# Generated by Django 5.1.3 on 2024-12-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0003_alter_encryptionhistory_decrypted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('decrypted_file_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
