# Generated by Django 5.1.3 on 2024-12-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0004_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
