# Generated by Django 5.1.3 on 2024-12-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0006_encryptionhistory_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_audio', models.FileField(upload_to='uploaded_audio/')),
                ('encrypted_audio', models.FileField(blank=True, null=True, upload_to='encrypted_audio/')),
                ('decrypted_audio', models.FileField(blank=True, null=True, upload_to='decrypted_audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='encryptionhistory',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
