# Generated by Django 5.1.3 on 2024-12-21 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0007_audiofile_alter_encryptionhistory_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
