# Generated by Django 5.1.3 on 2024-12-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0009_remove_fileupload_decrypted_file_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
