# Generated by Django 5.1.3 on 2024-12-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0010_delete_audiofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/original/')),
                ('encrypted_image', models.ImageField(blank=True, null=True, upload_to='images/encrypted/')),
                ('key', models.CharField(max_length=255)),
            ],
        ),
    ]
