# Generated by Django 5.1.3 on 2024-12-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0011_encryptedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedimage',
            name='encrypted_image',
            field=models.ImageField(blank=True, null=True, upload_to='encrypted_images/'),
        ),
        migrations.AlterField(
            model_name='encryptedimage',
            name='original_image',
            field=models.ImageField(upload_to='original_images/'),
        ),
    ]
