# Generated by Django 5.1.3 on 2024-12-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0012_alter_encryptedimage_encrypted_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='uploaded_audios/')),
                ('password', models.CharField(default='default_password', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_audio', models.FileField(blank=True, null=True, upload_to='encrypted_audios/')),
                ('decrypted_audio', models.FileField(blank=True, null=True, upload_to='decrypted_audios/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('decrypted_image', models.ImageField(blank=True, null=True, upload_to='decrypted_images/')),
                ('password', models.CharField(max_length=255)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
