# Generated by Django 5.1.3 on 2024-12-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0014_rename_decrypted_audio_audioupload_decrypted_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioupload',
            old_name='decrypted_file',
            new_name='decrypted_audio',
        ),
        migrations.RenameField(
            model_name='audioupload',
            old_name='encrypted_file',
            new_name='encrypted_audio',
        ),
    ]
