# Generated by Django 5.1.3 on 2024-12-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0015_rename_decrypted_file_audioupload_decrypted_audio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioupload',
            old_name='decrypted_audio',
            new_name='decrypted_file',
        ),
        migrations.RenameField(
            model_name='audioupload',
            old_name='encrypted_audio',
            new_name='encrypted_file',
        ),
    ]
