# Generated by Django 5.1.3 on 2024-12-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0017_rename_decrypted_file_audioupload_decrypted_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioupload',
            name='decrypted_audio',
            field=models.FileField(blank=True, null=True, upload_to='decrypted_audios/', verbose_name='Decrypted Audio File'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='encrypted_audio',
            field=models.FileField(blank=True, null=True, upload_to='encrypted_audios/', verbose_name='Encrypted Audio File'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='file',
            field=models.FileField(upload_to='uploaded_audios/', verbose_name='Original Audio File'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='password',
            field=models.CharField(default='default_password', max_length=100, verbose_name='Password for Encryption/Decryption'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload Timestamp'),
        ),
    ]
