# Generated by Django 5.1.3 on 2024-12-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0018_alter_audioupload_decrypted_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehistory',
            name='decrypted_image',
        ),
        migrations.RemoveField(
            model_name='imagehistory',
            name='password',
        ),
        migrations.AddField(
            model_name='imagehistory',
            name='decrypted_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagehistory',
            name='decryption_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
