# Generated by Django 5.1.3 on 2024-12-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0019_remove_imagehistory_decrypted_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehistory',
            name='date_uploaded',
        ),
    ]
