# Generated by Django 5.1.3 on 2024-12-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0020_remove_imagehistory_date_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagehistory',
            old_name='decryption_key',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='imagehistory',
            name='decrypted_image_base64',
        ),
        migrations.AddField(
            model_name='imagehistory',
            name='decrypted_image',
            field=models.ImageField(blank=True, null=True, upload_to='decrypted_images/'),
        ),
    ]
