# Generated by Django 5.1.3 on 2024-12-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0021_rename_decryption_key_imagehistory_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_videos/', verbose_name='Original Video File')),
                ('password', models.CharField(default='default_password', max_length=100, verbose_name='Password for Encryption/Decryption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload Timestamp')),
                ('encrypted_video', models.FileField(blank=True, null=True, upload_to='encrypted_videos/', verbose_name='Encrypted Video File')),
                ('decrypted_video', models.FileField(blank=True, null=True, upload_to='decrypted_videos/', verbose_name='Decrypted Video File')),
            ],
        ),
    ]
