# Generated by Django 5.1.3 on 2024-12-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0022_videoupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagehistory',
            old_name='decrypted_image',
            new_name='decrypted_image_base64',
        ),
    ]
