# Generated by Django 5.1.3 on 2024-12-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0024_remove_imagehistory_original_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehistory',
            name='encrypted_image',
        ),
        migrations.RemoveField(
            model_name='imagehistory',
            name='password',
        ),
        migrations.AddField(
            model_name='imagehistory',
            name='key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='imagehistory',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='original_images/'),
        ),
        migrations.AlterField(
            model_name='imagehistory',
            name='decrypted_image_base64',
            field=models.ImageField(blank=True, null=True, upload_to='decrypted_images/'),
        ),
    ]
